---
name: Build and Push Node.js Docker Image to GCP
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push Docker Image to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: c24-mr01-server
      PROJECT_ID: c24mr01-movie-rec
      REGION: asia-southeast2
      KMS_KEYRING: service-account-key
      KMS_KEY: firebase-service-account
      ENCRYPTED_JSON_FILE: gs://c24-mr01-kms/serviceAccountKey.json.enc
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Google Cloud Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Download and Decrypt Service Account JSON
        run: |
          gsutil cp $ENCRYPTED_JSON_FILE ./serviceAccountKey.json.enc
          gcloud kms decrypt \
            --location=$REGION \
            --keyring=$KMS_KEYRING \
            --key=$KMS_KEY \
            --ciphertext-file=./serviceAccountKey.json.enc \
            --plaintext-file=./key/serviceAccountKey.json

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash ./scripts/git_update.sh -v patch

    - name: Configure Docker Client
      run : |-
        gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest asia-southeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest asia-southeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker push asia-southeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push asia-southeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy c24-mr01-server \
          --image asia-southeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest \
          --platform managed \
          --region asia-southeast2 \
          --allow-unauthenticated \
          --set-env-vars JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --set-env-vars MOVIEDB_API_KEY=${{ secrets.MOVIEDB_API_KEY }}