---
name: Build and Push Node.js Docker Image to GCP
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push Docker Image to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: c24-mr01-server
      PROJECT_ID: c24mr01-movie-rec
      REGION: asia-southeast2
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: 'google-github-actions/setup-gcloud@v2'
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run : |-
        gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest asia-southeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest asia-southeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker push asia-southeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push asia-southeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG

    - name: Deploy to Cloud Run
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      run: |
        mkdir -p key
        echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }} > key/serviceAccountKey.json
        gcloud run deploy $IMAGE_NAME \
          --image asia-southeast2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars JWT_SECRET=${{ secrets.JWT_SECRET }},MOVIEDB_API_KEY=${{ secrets.MOVIEDB_API_KEY }}